name: Matrix Workflow
on: push

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
    steps:
      - run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
